---
title: "presentation R Project"
author:
date: May 14, 2020
output:
  ioslides_presentation:
    widescreen: true
---
## R Project

**Prostate Cancer Data Analysis**

- The Datasets
- Cleaning
- Tidying
- Visualizing the Data
- What to look for
- PCA and Clustering
- Regression
- Classification

## The Datasets

**Prostate Cancer Data**

  What variables what do they mean?
  
## The Datasets

**TCGA Datasets**

- Two datasets 
  What variables what do they mean?
  
## Cleaning and Tidying Prostate Cancer Data
- Changing names(no spaces, reasonable for the content, no cap letters)
```{r,  eval=FALSE}
## Prostate_raw cleaning

# changing column names
prostate_clean <- prostate_raw %>% 
  rename("patient_id" = "patno", "estrogen_mg" = "rx", "months_fu" = "dtime",
          "weight_index" = "wt", "activity_level" = "pf", "cv_history" = "hx",
          "serum_hg" = "hg", "tumour_size" = "sz", "bone_metastases" = "bm",
          "date_on_study" = "sdate")
```

- Removing rows with missing values
- Modifying estrogen_mg column removing the str "mg estrogen" (the column has been split in to two columns one of interest and the other one that was deleted, the two columns have been split using the separator str "mg")
- The column has then been transformed into a double with the command as.numeric because it was a string
- The variable date has been converted to a more readable date format (conversion from R coding of the dates to numbers that represent the distance from a certain initial date)
-
## Cleaning and Tidying TCGA Dataset
- Changing names(no spaces, reasonable for the content, no cap letters)
- (what about deleting the rows with missing values)
- 
## Augment Prostate Cancer Data
- Added column to identify the dataset
- One Hot Encoding for each variable defining classes
- Redefining classes for survival (The information we want to get from the data is the division between the patients that died for prostate cancer, for other causes and the ones that are still alive, we don't care about the distinction between the other causes of death)
## Augment TCGA Dataset
- Added column to identify the dataset
- One Hot Encoding for each variable defining classes
- Convert the content of the os_time from days to months to compare to months_fu in PCD
- Binarize bone_scan_results to compare to bone_metastases in PCD
- Obtain sg value from gleason score
- Select columns in common between the TCGA Dataset and the Prostate Cancer Dataset

## Joining the datasets
- anti_join to check if we are missing any information in the joining
- Inner_join between the TCGA datasets to have a TCGA Dataset
- Full_join to merge the TCGA Dataset and the Prostate Cancer Dataset
## Visualizing the Data
-comment plots
## What to look for
- REGRESSION : we want to find a function to predict the survival of the patients basing on other variables(choose the variables looking at the scatterplots)
- CLASSIFICATION we want to predict if a patient is going to survive or to die from prostate cancer or die from other causes 
## PCA and Clustering
- 
## Regression
-
## Classification




